version: 2
updates:
  
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5

  
  - package-ecosystem: "maven"
    directory: "/backend"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5
